[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
evm_version = 'shanghai'
extra_output_files = ['metadata']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default.rpc_endpoints]
ethereum = "https://mainnet.infura.io/v3/<API_KEY>"
goerli = "https://goerli.infura.io/v3/<API_KEY>"

[profile.default.etherscan]
ethereum = { key = "<API_KEY>", chain=1}
goerli = { key = "<API_KEY>", chain=5, url ="https://api-goerli.etherscan.io/api"}